#+TITLE: Nix Machines

* Table of Contents :TOC_3:
- [[#introduction][Introduction]]
- [[#instructions][Instructions]]
  - [[#mac-os][Mac OS]]
    - [[#installation][Installation]]
    - [[#uninstallation][Uninstallation]]
- [[#hosts][Hosts]]

* Introduction
This repository is an on-going effort to move my dotfiles to ~nix~ package manager
from ~homebrew~. Nix is a purely functional language and package manager.

* Instructions
Currently, there is a bootstrap script for Mac OS. I need to add scripts for
Linux machines as well.
** Mac OS
*** Installation
1. Clone this repository to a directory of your choice. I usually clone it in
   ~$xdg_config_home/nixpkgs~.
2. Ensure there exist a flake for the current host and username (check out
   ~flake.nix~ for the complete list).
   + If setting up a new system: 
     1) Create a new directory with the machine's host name in 
        ~modules/hosts/HOST_NAME~ and copy ~configuration.nix~ 
        and ~home.nix~ from some other host directory to the newly created one.
        Then, modify the configuration files per liking.
     2) Add the newly created files to git. There is no need to commit the
        changes at this point.
     3) Create a new flake entry in ~flake.nix~. 
3. ~cd~ to the repo directory and run:
   #+BEGIN_SRC bash
   bin/yo-mac-installer install $HOST
   #+END_SRC
4. You may need to reboot the system -- specially if ~skhd~ is not working.
*** Uninstallation
To uninstall nix simply run:
#+BEGIN_SRC bash
bin/yo-mac-installer uninstall
#+END_SRC
Note this will not remove the nix configuration files.

* Hosts
| Host      | OS     | Notes                   |
|-----------+--------+-------------------------|
| zebra.lan | Darwin | My personal MacBook Pro |
